# Netlify configuration for Black Alsatian

[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "22"
  # Keep CI output clean and installs fast; .npmrc handles legacy peer deps
  NPM_FLAGS = "--no-audit --no-fund"

# Global security headers
# Headers moved to generated public/_headers to avoid conflicts and allow env-driven values.
